# default config for ESH is avaliable on the GitHub Repository. You will experience issues with a broken config.
title = "esh"

[colours]
# Use ANSI escape sequences.
## https://en.wikipedia.org/wiki/ANSI_escape_code
## You can disable colours by changing the below VALUE to 'false'.
enabled = true
files = "\033[91m" # Red
directories = "\033[93m" #  Yellow

[system]
# used for system specific operations.

#EDIT ME
## This will be your home directory, '{username}' will automatically be replaced with your username.
homedir = ""
#homedir = "/home/{username}" 
#homedir = "C:\Users\{username}"

#Use a tilda ( ~ ) for referencing your home directory - as set above.
usetilde = false
